version: "3.8"

services:
  micro1:
    build: ./microservices/micro1
    ports:
      - "5001:3001"

  micro2:
    build: ./microservices/micro2
    ports:
      - "5002:3002"

  gateway:
    build: ./gateway
    ports:
      - "5000:3000"
    depends_on:
      - micro1
      - micro2
